services:
  - type: web
    name: sci-fi-be
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: sci-fi
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: BCRYPT_SALT_ROUNDS
        value: "10"

